language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: fstiehle-github
    token:
      secure: alo+dT880VrGzO8vll18wEW1uDz2HCWYs7UwXKGlXM1jy+C/w8zogkHNBdJVxjNKa3r07qnb55hM0jhwqIhovya2CtKv5x4LJ2karUD1PlEbiGSOSwumU7QjnvnRieACQ1whA5UhbfNeUIgsCUi1D4a6ZH5NISwiDaP5QQgz9lGS6aop9/NRbGGCt0TVw1XincYvNsVVzHP7Wcn2D30n0Wv8YiCFdxQ2h1hmPP0VBeTG+qvDVlhFl5hho5R49BIkc3m4TYiCZLwaLya2wqo99LtzKRUXWgFIenMVCKvKuXTqdNr+fhrg0mYmF7A0pHkfHbgS9wwtkJQOq+eT5nbNDwNHR+egVWw4gMtyLOvyFjPuq3hiw5uLYSgs2URjPn6OspMw5pGtyvCH48p1bl4Qm1NJHAagw22IVPwnCzVqgDPCPz6DhhZAMlN7uMsG9R9gxBYj+6yHC42HbvxulTM+NOgJk8msBSRuonqehlUz8MP65K18zlgbelWqW3jzUSbmkUxfnW2T7hqF3zKWuCJawEwKPLCSEwpP+fHiUOYQVC5Y0jBKXUKbctjt+B4snihZkxaXInMrGix5jqg3jWb5uJH8bvDuUTzifGhyiCUARnH6BuAI9XKziU+zXUBBin55eiNv/f5dnCDt7tdJB+xUs+z+grc//MwoHku8uaXW2t8=

jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
env:
  matrix:
    secure: alo+dT880VrGzO8vll18wEW1uDz2HCWYs7UwXKGlXM1jy+C/w8zogkHNBdJVxjNKa3r07qnb55hM0jhwqIhovya2CtKv5x4LJ2karUD1PlEbiGSOSwumU7QjnvnRieACQ1whA5UhbfNeUIgsCUi1D4a6ZH5NISwiDaP5QQgz9lGS6aop9/NRbGGCt0TVw1XincYvNsVVzHP7Wcn2D30n0Wv8YiCFdxQ2h1hmPP0VBeTG+qvDVlhFl5hho5R49BIkc3m4TYiCZLwaLya2wqo99LtzKRUXWgFIenMVCKvKuXTqdNr+fhrg0mYmF7A0pHkfHbgS9wwtkJQOq+eT5nbNDwNHR+egVWw4gMtyLOvyFjPuq3hiw5uLYSgs2URjPn6OspMw5pGtyvCH48p1bl4Qm1NJHAagw22IVPwnCzVqgDPCPz6DhhZAMlN7uMsG9R9gxBYj+6yHC42HbvxulTM+NOgJk8msBSRuonqehlUz8MP65K18zlgbelWqW3jzUSbmkUxfnW2T7hqF3zKWuCJawEwKPLCSEwpP+fHiUOYQVC5Y0jBKXUKbctjt+B4snihZkxaXInMrGix5jqg3jWb5uJH8bvDuUTzifGhyiCUARnH6BuAI9XKziU+zXUBBin55eiNv/f5dnCDt7tdJB+xUs+z+grc//MwoHku8uaXW2t8=
